### ISSUE TITLE
Many of the links in the Mage Training Arena plugin page are broken.

### ISSUE THREAD

**Issue by indomara** [runelite/wiki#82]
There are references to settings which don't exist in the current plugin settings like "[The plugin also offers the ability to instead of one tile draw the line of tiles on which you are able to stand to correctly cast the spell.](https://camo.githubusercontent.com/d97c1968c37f72074ea5493e3721dfcb2a0d71cc/68747470733a2f2f692e696d6775722e636f6d2f677530346d72672e706e67)" or "[The plugin also allows you to change from icons to text.](https://camo.githubusercontent.com/17ae8dd1f6acd6bfcf478152c5d796aaafda5bb7/68747470733a2f2f692e696d6775722e636f6d2f7647624b4c39302e706e67)" or  "[This overlay will add a counter infobox displaying how many fruit your bones will get you and the color changes depending on whether this is enough for a point.](https://camo.githubusercontent.com/fa880c0804775ced574f3244d8a340701a5baf95/68747470733a2f2f692e696d6775722e636f6d2f665448324f62622e706e67)".

I was interested in using these settings but my plugin settings only offer the ability to turn on and off in the various rooms.

Edit: Sorry the link to the wiki page I am referring to is: https://github.com/runelite/runelite/wiki/Mage-Training-Arena

**Comment by Felanbird** [comment]
This would have been fixed by #68 but it fell in my TODO pile, I've gone ahead and cherry-picked out the MTA changes here b6cb7b311b1a7b741bbe12601de0650e205226c7

The page might need an update due to the recent game changes, I haven't had a chance to look at what changes Adam has made for the next RuneLite version, when that comes out if anything seems incorrect feel free to open a new issue.

**Comment by indomara** [comment]
Thank you very much for all your work, I really appreciate it.
